server:
  port: 8761
#服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
#注意，EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，这个配置一般为服务刷新时间配置的三倍
#默认90s
#服务刷新时间配置，每隔这个时间会主动心跳一次
#默认30s eureka.instance.lease-renewal-interval-in-seconds=5
eureka:
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 4000
  instance:
    prefer-ip-address: true
    hostname: localhost
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://easysass:easysass123@localhost:${server.port}/eureka/
# 安全认证的配置  
spring:
  security:
    basic:
      enabled: true
    user: 
      name: easysass
      password: easysass123
#spring.cloud.config.discovery.enabled: true